name: 开始每日随机签到

on:
  workflow_dispatch:
  schedule:
    # 每天UTC的0点(北京时间8点)触发，然后通过脚本随机延迟执行
    - cron: '0 0 * * *'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Generate random delay
        id: delay
        run: |
          # 生成一个随机的小时数和分钟数，小时在0到1之间
          # HOUR=$(shuf -i 0 -n 1)
          MINUTE=$(shuf -i 0-50 -n 1)
          # 计算总延迟时间（以秒为单位）
          # DELAY=$((HOUR * 3600 + MINUTE * 60))
          DELAY=$((MINUTE * 60))
          #echo "Random delay of $HOUR hours and $MINUTE minutes"
          echo "Random delay of $MINUTE minutes"
          echo "::set-output name=delay::$DELAY"
      - name: Sleep for random time
        run: |
          DELAY=${{ steps.delay.outputs.delay }}
          echo "Sleeping for $DELAY seconds"
          sleep $DELAY
      - name: Run checkin
        run: |
          python3 glados.py
        env: 
          GLADOS_COOKIE: "${{ secrets.GLADOS_COOKIE }}"
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}"
      - uses: gautamkrishnar/keepalive-workflow@master  
